[server]
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[theme]
base = "dark"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#e6edf3"
primaryColor = "#ff5b1f"

[ui]
hideSidebarNav = true
